---
grails:
    profile: web
    codegen:
        defaultPackage: mds
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 1342177280
            maxRequestSize: 1342177280
    converters:
        encoding: UTF-8
    databinding:
        autoGrowCollectionLimit: 8192
    web:
        url:
            converter: hyphenated
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        dialect: ai.boost.sql.PgBoostDialect
    #default_schema: public

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: ai.boost.sql.PgBoostDialect

environments:
    development:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/adminpanel
            username: boost
            password: boost
        dataSources:
            qa:
                dbCreate: none
                username: boostqa
                password: boostqa
                url: jdbc:postgresql://localhost:5432/adminpanel
                transactional: true

    test:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/adminpanel_test
            username: boosttest
            password: boosttest
            properties:
                initialSize: 2
                maxActive: 5
                minIdle: 2
                maxIdle: 5
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                setQueryTimeout: 10000
    production:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/adminpanel2
            username: boost
            password: boost
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 5
                minIdle: 5
                maxIdle: 10
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
